MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'ResNext'
        PRETRAINED: True
        INPUT_CHANNELS: 3
        OUT_CHANNELS: [512, 1024, 2048]
    PRIORS:
        FEATURE_MAPS: [[50, 75], [25, 38], [13, 19]]
        STRIDES : [[8, 8], [16, 16], [32, 32], [64, 64], [100, 100], [300, 300]]
        MIN_SIZES: [[30, 30], [60, 60], [111, 111], [162, 162], [213, 213], [264, 264]] #FØR [20,20] --> SISTE ENDRING [30, 30] 
        MAX_SIZES: [[60, 60], [111, 111], [162, 162], [213, 213], [264, 264], [315, 315]]
        ASPECT_RATIOS: [[2], [2, 3], [2, 3], [2, 3], [2], [2]]
        BOXES_PER_LOCATION: [4, 6, 6, 6, 4, 4]
        
        
        #hOW TO rescale min and max to fit image resolution:
        #[[0.1X, 0.1Y], [0.2X, 0.2Y], [0.37X, 0.37Y], [0.54X, 0.54Y], [0.71X, 0.71Y], [0.88X, 0.88Y]] min
        #[[0.2X, 0.2Y], [0.37X, 0.37Y], [0.54X, 0.54Y], [0.71X, 0.71Y], [0.88X, 0.88Y], [1.05X,1.05Y]] max
        # [300/38 500/63], 300/19 500/32, etc.. stride image res/features
INPUT:
    IMAGE_SIZE: [400, 600]
    # std, mean from: https://pytorch.org/hub/pytorch_vision_resnext/
    PIXEL_STD: [0.229, 0.224, 0.225] # since we are pre-trained 
    PIXEL_MEAN: [123.675, 116.28, 103.53] # since we are pre-trained
DATASETS:
    TRAIN: ("rdd2020_train",)
    TEST: ("rdd2020_val",)
SOLVER:
    MAX_ITER: 10000
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 5e-4 #lower to 5e-3 after 10K
    WEIGHT_DECAY: 1e-2 #AFTER 10K
OUTPUT_DIR: 'outputs/ResNext_400x600'
DATASET_DIR: "/work/datasets/"
EVAL_STEP: 1000
MODEL_SAVE_STEP: 1000