MODEL: 
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'basic'
        PRETRAINED: True
        OUT_CHANNELS: [256, 512, 256, 256, 128, 128]
        INPUT_CHANNELS: 3
INPUT:
    IMAGE_SIZE: [300, 300]
DATASETS:
    TRAIN: ("tdt4265_train",)
    TEST: ("tdt4265_val", )
SOLVER:
    MAX_ITER: 20000
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 5e-4
OUTPUT_DIR: 'outputs/tdt4265'
DATASET_DIR: "datasets"