MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'vgg'
        PRETRAINED: True
        INPUT_CHANNELS: 3
    THRESHOLD: 0.55
    PRIORS:
        FEATURE_MAPS:  [[38,38], [19, 19], [10, 10],[5,5],[3,3],[1,1]]
        MIN_SIZES: [[20, 20], [60, 60], [111, 111], [162, 162], [213, 213], [264, 264]]
        MAX_SIZES: [[60, 60], [111, 111], [162, 162], [213, 213], [264, 264], [315, 315]]
        ASPECT_RATIOS: [[2], [2, 3], [2, 3], [2, 3], [2], [2]]
INPUT:
    IMAGE_SIZE: [300, 300]
    PIXEL_STD: [0.003921569, 0.003921569, 0.003921569] # Set pixel std to 1/255 as VGG is pre-trained on images in range (roughly) [-127.5, 127.5]
    
DATASETS:
    TRAIN: ("rdd2020_train",)
    TEST: ("rdd2020_val", )
SOLVER:
    MAX_ITER: 40000
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 5e-4
  
OUTPUT_DIR: 'outputs/vgg_RDD2020'
EVAL_STEP: 2500
MODEL_SAVE_STEP: 2500
DATASET_DIR: "/work/datasets/"